---
# vim: set ft=ansible:
#
# Installs an RPM using a URL
#
# Parameters
#   rpm_url (required) [string] - full url to rpm
#
- name: Fail if rpm_url is undefined
  fail:
    msg: "rpm_url must be passed into this role/include"
  when: rpm_url is undefined

- name: Install {{ rpm_url }}
  command:  rpm -i {{ rpm_url }}
